---
routers:
  platform: cisco_ios
  username: cisco
  password: cisco
  connection_options:
    netmiko:
      extras:
        device_type: cisco_ios_telnet

switches:
  platform: cisco_ios
  username: cisco
  password: cisco
  connection_options:
    netmiko:
      extras:
        device_type: cisco_ios_telnet
