# Lab02 - Netmiko OOP Loopback Lab
# Adjust IPs after EVE-NG lab is created
routers:
  - host: 10.255.1.101
    hostname: R1
    interface: Loopback10
    loopback_ip: 1.1.1.1
    description: Loopback for R1
  - host: 10.255.1.102
    hostname: R2
    interface: Loopback10
    loopback_ip: 2.2.2.2
    description: Loopback for R2
  - host: 10.255.1.103
    hostname: R3
    interface: Loopback10
    loopback_ip: 3.3.3.3
    description: Loopback for R3

credentials:
  username: admin
  password: admin123
